<?php

// $Id$

/**
 * This function builds the form elements for the file formater based
 * on the node type and field for settings and the file extension to get the formaters 
 * @param string $node_type
 *   the kind of node
 * @param string $field
 *   the machine name of the field being operated on
 * @param string $uri
 *   the uri to the item, or file://path if it is being uploaded
 * @param string $file_extension
 *   the kind of file that will be operated on
 */
function media_ajax_formater_load($node_type, $field, $uri = 'file://', $file_extension) {
  // we need to check the adminstrative settings for this 
  // node tyi
  

}
