<?php
// $Id$

/**
 * @file
 * Media API
 *
 * The core Media API.
 * The Media module provides a drop-in replacement for Drupal's Upload,
 * FileField, Embedded Media Field, and other similar forms. It offers an API
 * and hooks available for other modules to implement, allowing for customized
 * file lists, tabs, drawers, and forms to the new Upload form.
 */

/* ***************************************** */
/* INCLUDES                                  */
/* ***************************************** */

include_once('media.types.inc');
include_once('media.fields.inc');
include_once('media.filter.inc'); // Code related to [[inline tags]] and wysiwyg

/* ***************************************** */
/* CONSTANTS                                 */
/* ***************************************** */

define('MEDIA_RESOURCE_URI_DEFAULT', 'public://');
define('MEDIA_TYPES_DEFAULT', '*');

/* ***************************************** */
/* DRUPAL API FUNCTIONS                      */
/* ***************************************** */

/**
 * Implementation of hook_menu().
 */
function media_menu() {

  // For managing different types of media and the fields associated with them.
  $items['admin/structure/media'] = array(
    'title' => 'Media Types',
    'description' => 'Manage files used on your site.',
    'page callback' => 'media_admin_type_list',
    'access arguments' => array('administer media'),
    'file' => 'media.admin.inc',
  );

  $items['admin/structure/media/manage/%media_type'] = array(
    'title' => 'Manage media',
    'description' => 'Manage files used on your site.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('media_admin_type_manage_form', 4),
    'access arguments' => array('administer media'),
    'type' => MENU_CALLBACK,
    'file' => 'media.admin.inc',
  );

  $items['admin/structure/media/manage/%media_type/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -1,
  );

  // Admin settings
  $items['admin/content/media'] = array(
    'title' => 'Media',
    'description' => 'Manage files used on your site.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('media_admin'),
    'access arguments' => array('administer media'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'media.admin.inc',
  );

  $items['admin/content/media/add/files'] = array(
    'title' => 'Upload new file',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('media_add_files'),
    'access arguments' => array('administer media'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'media.admin.inc',
    'weight' => -1,
  );

  $items['admin/content/media/add/from_url'] = array(
    'title' => 'Add media from URL',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('media_add_fromurl'),
    'access arguments' => array('administer media'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'media.admin.inc',
    'weight' => -1,
  );

  /**
   * Media Browser related callbacks
   * @var unknown_type
   */

  $items['media/browser'] = array(
    'title'            => 'Media browser',
    'description'      => 'Media Browser for picking media and uploading new media',
    'page callback'    => 'media_browser',
    'access arguments' => array('use media browser'),
    'weight'           => 3,
    'type'             => MENU_CALLBACK,
    'file'             => 'media.admin.inc',
  );

  $items['media/browser/list'] = array(
    'title'            => 'Media browser list',
    'description'      => 'Ajax Callback for getting media',
    'page callback'    => 'media_browser_list',
    'access arguments' => array('use media browser'),
    'weight'           => 3,
    'type'             => MENU_CALLBACK,
    'file'             => 'media.admin.inc',
  );

  $items['media/browser/library'] = array(
    'title'            => 'Media browser library',
    'description'      => 'Media Browser for picking media and uploading new media',
    'page callback'    => 'media_browser_library',
    'access arguments' => array('use media browser'),
    'weight'           => 3,
    'type'             => MENU_CALLBACK,
    'file'             => 'media.admin.inc',
  );

  //@todo: make this more like node?  (End user facing)

  $items['media'] = array(
    'title' => 'Media',
    'page callback' => 'media_page_default',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['media/%media'] = array(
    'title'           => 'Media view',
    'description'     => 'View an individual media item',
    'page callback'   => 'media_file_view',
    'page arguments'  => array(1),
    'access arguments' => array('access content'), //array('view media'),
    'type' => MENU_CALLBACK,
  );

  $items['media/%media/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $items['media/%media/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'media_page_edit',
    'page arguments'  => array(1),
    'access arguments' => array('edit media'), //@todo: add this permission
    'weight' => 0,
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'media.admin.inc'
  );

  $items['media/%media/format-form'] = array(
    'title' => 'Format form',
    'description' => 'Used as an AJAX callback',
    'page callback' => 'media_browser_format',
    'page arguments' => array(1),
    'access arguments' => array('administer media'),
    'weight' => 0,
    'type' => MENU_CALLBACK,
    'file' => 'media.admin.inc',
  );

  return $items;
}

/**
 * Loads a Media Asset
 *
 * @param $fid
 * @return StdClass
 */
function media_load($fid) {
  if ($files = entity_load('media', array($fid))) {
    return array_shift($files);
  }
}

/**
 * Save a Media Asset
 *
 * @param $media
 * @return StdClass
 */
function media_save($media) {
  field_attach_presave('media', $media);
  if ($media->fid) {
    $op = 'update';
  }
  else {
    $op = 'insert';
  }
  // Do something here for insert update
  if ($op == 'insert') {
    // should never happen I think, except perhaps on import.
    // @todo: validate bundle, etc
    field_attach_insert('media', $media);
  }
  else {
    field_attach_update('media', $media);
  }
}


/* ***************************************** */
/* Media Hook Implementations                */
/* ***************************************** */


/**
 * Implement hook_permission().
 */
function media_permission() {
  return array(
    'administer media' => array(
      'title' => t('Administer media'),
      'description' => t('Add, edit or delete media.'),
    ),
  );
}

/**
 * Implements hook_theme().
 * Register theming functions
 * @todo: remove cruft
 *
 * @return array
 */
function media_theme() {
  return array(
    'media_managed_file' => array(
      'render element' => 'element',
    ),

    // The media file browser form.
    'media_file_browser' => array(
      'variables'          => array('element' => NULL),
    ),

    // The default media file list form element.
    'media_file_list' => array(
      'variables'       => array('element' => NULL),
    ),

    // The media browser pane.
    'media_browser_pane' => array(
      'variables'         => array('form' => array()),
    ),

    // A link for a file w/ an icon to the media/$fid page.
    'media_link' => array(
      'variables'         => array('file' => NULL),
      'file'              => 'media.theme.inc',
    ),

    // A preview of the uploaded file.
    'media_admin_thumbnail' => array(
      'variables' => array('file' => NULL, 'style_name' => 'thumbnail'),
      'file' => 'media.theme.inc',
    ),

    // Administrative thumbnail previews.
    'media_admin_thumbnail' => array(
      'variables' => array('files' => array(), 'style_name' => 'thumbnail'),
      'file' => 'media.theme.inc',
    ),

    // Tabs in the media browser.
    'media_browser_tabs' => array(
      'file' => 'media.theme.inc',
    ),
  );
}

/**
 *  Implementation of hook_media_elements().
 *
 *  A Media File List element is created with the following FAPI:
 *    '#type' => 'media_file_list',
 *    '#options' => $options,         // An associative array of filepaths, keyed by FID.
 *    '#title' => $title,             // The translated title, displayed in the tab.
 *    '#description' => $description, // A translated description, to be displayed below the title.
 */
function media_elements() {
  $elements = array();

  $elements['media_file_list'] = array(
    '#input'            => TRUE,
    '#process'          => array('media_file_list_element_process'),
    '#element_validate' => array('media_file_list_element_validate'),
    '#submit'           => array('media_file_list_element_submit'),
  );

  return $elements;
}

/* *************************************************** */
/* Media forms                                         */
/* *************************************************** */

/**
 * Build data for the media browser display.
 *
 * @TODO Pick what we can from this and remove.
 *
 * Note: The FAPI docs say a submit element event defaults to 'click',
 * but as of d6.10, it defaults to 'mousedown', so we need to override.
 *   'event' => 'click',
 *
 * @param array $registration_ids
 *   Array of registrations to call.
 * @param string $node_type
 * @param string $field
 * @param uid $uid
 * @return array
 *   Drupal FAPI form array.
 */
function media_build_browser_form($form_state, $registration_ids, $node_type, $field, $uid) {
  static $id;

  // We need a static counter for our form element wrapper.
  $id += 1;

  // Load our css.
  $path = drupal_get_path('module', 'media');
  drupal_add_css($path .'/media.css');
  // Load our specific js for the file selector
  drupal_add_js($path .'/javascript/media.js');
  // Load the md5 library so we can hash the upload filename for use in the meta form.
  drupal_add_js($path .'/javascript/jquery.md5.js');

  $items = array();
  $form  = array();

  $form['media_browser_activate'] = array(
    '#type'  => 'markup',
    '#value' => '<div class="media browser activation">'. t('Add files') .'</div>',
  );

  // We are using a tab form type.
  $form['media_browser'] = array(
    '#type'       => 'tabset',
    '#attributes' => array('class' => 'media browser wrapper'),
  );

  // Get all the active resources
  $resources = media_get_resources($registration_ids, $node_type, $field, $uid);

  // Store the tab & drawer names for the js form selector.
  $drawer_options = array();

  // loop through the form and start pulling out the data to
  // create tabs -> panes -> drawers
  foreach ($resources as $tab_name => $data) {
    // create a tab id
    $tab_id = strtolower(str_replace(' ', '_', $tab_name));
    // create tab
    $form['media_browser'][$tab_id] = array(
      '#type'  => 'tabpage',
      '#title' => $tab_name,
      '#theme' => 'media_browser_pane',
    );

    $drawer_options[$tab_id] = $tab_name;

    // build the drawers for this tab
    $drawer_list   = array();
    $active_drawer = TRUE;

    // check to see if we do have children- we should, but just in case
    if (is_array($data)) {
      $drawers = array();

      foreach ($data as $drawer_name => $drawer_data) {
        // @TODO check drawer access permissions here to make sure we should present this to the user

        // The drawer id needs to have additional data on it to prevent
        // name space conflicts with ids
        $drawer_id = strtolower(str_replace(' ', '_', $drawer_name)) .'_display';

        // create a link with a specific id to call
        $drawers_link  = '<a onclick="javascript: return FALSE;" href="#'. $drawer_id .'">'. $drawer_name .'</a>';
        $drawer_list[] = array('data' => $drawers_link, 'class' =>  ($active_drawer ? 'active' : '') );

        // add the drawer form element
        $form['media_browser'][$tab_id][$drawer_name] = $drawer_data;

        // add classes to the drawer display item
        $form['media_browser'][$tab_id][$drawer_name]['#prefix'] = '<div id="'. $drawer_id .'" class="drawer display '. ($active_drawer ? ' active' : NULL) .'">';
        $form['media_browser'][$tab_id][$drawer_name]['#suffix'] = '</div>';

        // no longer on the first drawer
        $active_drawer = FALSE;

        $drawer_options[$tab_id .'|'. $drawer_id] = '- '. $drawer_name;
      }

      // change the drawers to a list for easer display
      $form['media_browser'][$tab_id]['drawers'] = array(
        '#type'  => 'markup',
        '#value' => theme('item_list', $drawer_list, NULL, 'ul', array('class' => 'drawers'))
      );

    }
  }

  $form['media_browser']['drawer_select'] = array(
    '#type'        => 'select',
    '#title'       => t('Drawer select'),
    '#description' => t('Oh bother, you really should have JavaScript enabled, you know...'),
    '#options'     => $drawer_options,
    '#prefix'      => '<div class="media-browser-drawer-select">',
    '#suffix'      => '</div>',
  );

  // Container for the progress indicator.
  $form['media_browser']['media_browser_file_progress'] = array(
    '#prefix' => '<div id="media-browser-file-progress-'. $id .'" class="media-browser-file-progress">',
    '#suffix' => '</div>',
  );
  $form['media_browser']['media_browser_file_progress']['file_progress_message'] = array(
    '#type'  => 'item',
    '#title' => theme('image', variable_get('media_file_progress_image', $path .'/images/uploading-gradient.gif')) . t('Please wait while your file is attached...'),
  );

  // AHAH enabled submit button.
  $form['media_browser']['media_browser_submit'] = array(
    '#type'        => 'submit',
    '#value'       => t('Add file'),
    '#description' => t("Add the selected file."),
    '#submit'      => array('media_browser_submit'), // If no javascript action.
    '#validate'    => array('media_browser_validate'),
    '#attributes'  => array('class' => 'media-browser-submit'),
    '#ahah'        => array(
      'path'         => 'media/js',
      'wrapper'      => 'media-browser-file-progress-'. $id,
      'method'       => 'replace',
      'effect'       => 'fade',
      'event'        => 'click',
    ),
  );

  // Container for the metadata submission message.
  $form['media_browser']['media_browser_metadata_message'] = array(
    '#prefix' => '<div id="media-browser-metadata-message-'. $id .'" class="media-browser-metadata-message">',
    '#suffix' => '</div>',
  );
  $form['media_browser']['media_browser_metadata_message']['message'] = array(
    '#type'  => 'item',
    '#value' => '',
  );

  $form['media_browser']['media_browser_metadata'] = array(
    '#type'       => 'tabset',
    '#attributes' => array('class' => 'media-browser-metadata-wrapper'),
  );

  // @TODO: This all goes in the form creation, actually,
  // to create our metadata form...
//   $uri = $form_state['values']['media_files'];
//   $file_extension = pathinfo($uri, PATHINFO_EXTENSION);
//
//   // Get the file creator for this item.
//   $file_creator = media_get_registered_modules(array($registration_id));
//
//   // Get the formaters for this node type.
//   $formatters = media_active_fields_for_node_type($node_type, 'formatter');
//
//   // Get the registrations.
//   $registrations = media_get_registered_modules($formatters[$field]);
//
//   // Remove any non-applying registrations.
//   $registrations = media_get_applicable_formatters($registrations, $file_extension);
//
//   // Get all the formatting forms.
//   $formatter_options = array();
//   $forms = array();
//   foreach ($registrations as $id => $registration) {
//     $formatter_options[$id] = $registration['name'];
//     $function = $registration['callbacks']['form'];
//     if (function_exists($function)) {
//       $forms[$id] = $function($node_type, $field, $file_extension, $uri);
//     }
//   }

  // @TODO: This is placeholder only.
  foreach (array('Video', 'Image', 'Audio', 'PDF') as $mime_type) {
    $form['media_browser']['media_browser_metadata'][$mime_type] = array(
      '#type'  => 'tabpage',
      '#title' => $mime_type,
    );
    $form['media_browser']['media_browser_metadata'][$mime_type][$mime_type .'_title'] = array(
      '#type'  => 'textfield',
      '#title' => t('Title'),
    );
  }

  // Our AHAH enabled submit button for the metadata.
  $form['media_browser']['media_browser_metadata_submit'] = array(
    '#type'        => 'submit',
    '#value'       => t('Add metadata'),
    '#description' => t("Add the selected file."),
    '#submit'      => array('media_browser_metadata_submit'), // If no javascript action.
    '#validate'    => array('media_browser_metadata_validate'),
    '#attributes'  => array('class' => 'media-browser-metadata-submit'),
    '#ahah'        => array(
      'path'         => 'media/metadata/js',
      'wrapper'      => 'media-browser-metadata-message-'. $id,
      'method'       => 'replace',
      'effect'       => 'fade',
      'event'        => 'click',
    ),
  );

  // build the tabs into a single form element
  // @TODO make sure we have children for each tab and remove any that
  //       we don't have data for
  $form['tabs'] = array(
    '#type'  => 'markup',
    '#value' => theme('item_list', $tabs, NULL, 'ul', array('class' => 'tabs')),
  );

  return $form;
}

/* ***************************************** */
/* Callbacks                                 */
/* ***************************************** */

/**
 * Process callback for the media_browser element.
 *
 * @param $element
 * @param $edit
 * @param $form_state
 * @param $form
 * @return array
 */
function media_file_list_element_process($element, $edit, $form_state, $form) {
  $element['list'] = array(
    '#type'     => 'select',
    '#options'  => $element['#options'],
    '#size'     => variable_get('media_file_list_size', 10),
  );

  return $element;
}

/**
 * Menu callback; view a single piece of media.
 * @todo: this.
 */
function media_file_view($media) {
  drupal_set_title($media->filename);
  $ret = media_build_multiple(array($media->fid => $media), 'media_original');
  return $ret;
}

/**
 * Construct a drupal_render() style array from an array of loaded media files.
 *
 * @param $files
 *   An array of nodes as returned by node_load_multiple().
 * @param $view_mode
 *   Build mode, e.g. 'full', 'teaser'...
 * @param $weight
 *   An integer representing the weight of the first file in the list.
 * @return
 *   An array in the format expected by drupal_render().
 */
function media_build_multiple($files, $view_mode = 'media_original', $weight = 0) {
  field_attach_prepare_view('media', $files, $view_mode);
  $build = array();
  foreach ($files as $file) {
    $build['media'][$file->fid] = field_attach_view('media', $file, $view_mode);
    $build['media'][$file->fid]['#weight'] = $weight;
    $weight++;
  }
  $build['media']['#sorted'] = TRUE;

  return $build;
}

/**
 * Implement hook_file_insert();
 */
function media_file_insert(&$file) {
  media_add_type_to_file($file);
}

/**
 * Implement hook_file_update();
 */
function media_file_update(&$file) {
  media_add_type_to_file($file);
}

/**
 * Adds the media type field to the files table.
 *
 * This currently depends on the mimetype of the file.
 *
 * @param unknown_type $file
 * @return unknown_type
 */
function media_add_type_to_file($file) {
  $file->type = media_get_type($file);
  drupal_write_record('file', $file, array('fid'));
}

function media_process_page(&$variables) {
  // @todo: implement this or drop it.
  return;
  // This sucks, but don't know how else to know it is a request for the browser
  $trail = menu_get_active_trail();
  $active = array_pop($trail);
  if ($active['page_callback'] == 'media_browser') {
    //@todo: make this actually work (it doesn't right now).
    //array_unshift($variables['template_files'], 'media-browser.page');
  }
}

function media_page_alter(&$page) {
  // This sucks, no way to remove the header in garland. :(
  // @todo: this needs to be a template
  if (isset($_GET['render']) && $_GET['render'] == 'media-browser') {
    foreach (element_children($page) as $element_name) {
      if ($element_name != 'content') {
        unset($page[$element_name]);
      }
    }
  }
}

if (!function_exists('file_uri_to_object')) {
  // @todo: get this committed http://drupal.org/node/685818

  /**
   * Returns a file object which can be passed to file_save().
   *
   * @param $uri
   *  A string containing the URI, path, or filename.
   * @return
   *  A file object, or FALSE on error.
   */
  function file_uri_to_object($uri) {
    global $user;
    $uri = file_stream_wrapper_uri_normalize($uri);
    $wrapper = file_stream_wrapper_get_instance_by_uri($uri);
    $file = new StdClass;
    $file->uid = $user->uid;
    $file->filename = basename($uri);
    $file->uri = $uri;
    $file->filemime = file_get_mimetype($uri);
    $file->filesize = filesize($uri);
    $file->timestamp = REQUEST_TIME;
    $file->status = FILE_STATUS_PERMANENT;
    return $file;
  }
}

/**
 * Implementation of hook_form_alter().
 * We assign a form #after_build processing callback that is executed
 * on all forms after they have been completely built, so that we can
 * take the content of the textarea to inject our tagMap in Drupal.settings
 * to access on node/edit/<nid> or block/configure forms.
 *
 * @see media_process_form()
 */

function media_form_alter(&$form, &$form_state) {
  $form['#after_build'][] = 'media_process_form';
}