<?php

// $Id$


/* ***************************************** */
/* DRUPAL API FUNCTIONS                      */
/* ***************************************** */


/**
 * Implementation of hook_menu.
 * 
 */
function media_menu() {
  // ajax formater 
  $items['media/ajax'] = array(
    'title' => 'media Ajax',
    'page callback' => 'media_ajax_formater_load',
    'access arguments' => array('access content'),
    'file' => 'media_ajax.inc',
  );
  return $items;
}


/**
 * Implementation of hook_form_alter
 * @param $form
 * @param $form_state
 * @param $form_id
 * 
 */
function media_form_alter (&$form, $form_state, $form_id) {
  global $user;
  
  // $check_js is wether or not the client has JS
  

  // get the formaters for specified type 
  
  //print_r(media_registration_item_formaters(null, media_registration_kinds('formater')));
  
  $form['test'] = media_get_user_file_options('', '', $user->uid);
 
  $form['test']['#weight'] = -9;
  
  // we only handle media stuff on the node add/edit form
  if (strstr($form_id, 'node_form') ) {
    
    // need to control display here
  
    
    // collect all the form elements we need to hide

    // fire hook
    
    // put these elements into JS
    //drupal_add_js($elements, 'inline');
    
    // load the media JS file
    //drupal_add_js(drupal_get_path('module', 'media') .'/media.js');
    
    // do we need to add a field to store data in?
    
  }
  
}


/**
 * Register theming functions
 * @return array
 */
function media_theme() {
  return array(
    'media_no_tabs_display' => array(
      'file' => 'media_theme.inc',
      'arguments' => array(
        'tabs' => NULL,
      ),
    ),
  );
}


/* ***************************************** */
/* media hook calls                          */
/* ***************************************** */


/**
 * Gets all of the modules which register with ReMiG
 */
function media_get_registered_modules() {
  static $registrations;
  if (! $registrations) {
    $registrations = array();
    // get all the modules which implement 
    foreach (module_implements('media_register') as $module) {
      $function = $module .'_media_register';
      // get all the registrations
      $registration = $function();
      // add the module name to each registration
      foreach (array_keys($function()) as $key) {
        $registration[$key]['module'] = $module;
      }
      $registrations = array_merge($registrations, $registration); 
    }
  }
  return $registrations;  
}


/**
 * Get all module data that uses the "media_user_files_select" hook
 *
 * @param string $node_type
 * @param string $field
 * @param uid $uid
 * @return array
 *   drupal form array
 */
function media_get_user_file_options($node_type, $field, $uid) {
  $items = array();
  $form = array();
  // get all the modules which implement file select options
  foreach (module_implements('media_user_files_select') as $module) {
    $function = $module .'_media_user_files_select';
    $items = array_merge($items, $function($node_type, $field, $uid));
  }
  // now we order modules into tabs structure
  // @TODO implement admin weighting here some how
  foreach ($items as $id => $item) {
    $name = key($item);
    // now create the sub element (drawer)
    $my_files_elements[$id][$name] = array(
      '#type' => 'markup',
      '#value' => '<div class="media drawer">'. $name .'</div>',
      '#attributes' => array('class' => 'media drawer'),
      'content' => $item[$name]['form'],
    );
  }    
  
  return media_tabs_form($my_files_elements);  
}


/**
 * This handles all the admin hooks that do not
 * require the passing of a file object. This does not use
 * module_invoke_all() so that the array of data can be 
 * keyed by the module name for ease of usage later
 * @param string $hook
 *  name of the hook being called
 * @return array
 *  array of data from each module that implements the hook
 */
function media_admin_extend($hook) {
  $data = array();
  // get a list of the modules that implement this hook
  foreach (module_implements($hook) as $module) {
    // add the data keyed by module name
    $data[$module] = module_invoke($module, $hook);
  }
  if (count($data)) {return $data; }
}


/**
 * This allows admins to to configure specific settings
 * per module for media.
 * @return array
 *   drupal form array
 */
function media_admin_module_options_settings_form() {
  if (! $options = media_admin_extend('media_admin_options_settings')) {
    drupal_set_message(t('Sorry, there are no modules which have configurable settings.'));
    return;
  }
  // build a fieldset per module
  foreach ($options as $module_name => $option) {
    $form[$module_name] = array(
      '#type' => 'fieldset',
      '#title' => $module_name
    );
    $form[$module_name][] = $options;
  }
  return $form;
}


/**
 * This takes all of the modules that implement the media permissions 
 * hook, gets them on a page, and adds a roll setting to control access
 * @return array
 *  drupal form array
 */
function media_admin_module_options_permissions_form() {
  // get any cached permissions for the permisisons 
  $permissions = unserialize(variable_get('media_admin_permissions', array()));
  if (! $options = media_admin_extend('media_admin_permissions_settings', $permissions)) {
    drupal_set_message(t('Sorry, there are no modules which have configurable permissions settings.'));
    return;
  }
  
  // build a fieldset per module
  foreach ($options as $module_name => $option) {
    $form[$module_name] = array(
      '#type' => 'fieldset',
      '#title' => $module_name
    );
    
    // create the roll form item
    $append = array(
      '#type' => 'select',
      '#title' => t('Permissions'),
      '#multiple' => true,
    );
    // now we need to itterate through the incoming form and append 
    // the roll setting to each item
    $form[$module_name] = _media_admin_form_perm_append($option, $append, $permissions['module']);
    
    $form[$module_name][] = $options;
  }
}


/**
 * This is a helper function to add in a permissions element 
 * for each of the options that are access
 * @param array $form
 *   the drupal form array that will have items appended to it
 * @param array $append
 *   the form element that will be appended to the form
 * @param array $permissions
 *   permissions saved for this module
 * @return array
 *   drupal form array
 */
function _media_admin_form_perm_append($form, $append, $permissions) {
  foreach ($form as $type => $element) {
    if ($type = '#title') {
      $form[$element .'_perm'] = $append;
      $form[$element .'_perm']['#default_value'] = $permissions[$element .'_perm'];
    }
    elseif (is_array($element)) {
      $form[$type][] = _media_admin_form_perm_append($element, $append, $permissions);
    }
  }
  return $form;
}


/* ***************************************** */
/* media Internal Functions                  */
/* ***************************************** */

/**
 * Parsing function for the registrations to hand back the kinds 
 * of modules registering. Used to select all formaters, containers, etc
 * @param string $kinds
 *   return all the matching registrations of this kind
 * @return array
 */
function media_registration_kinds($kind = null) {
  $kinds = array();
  // get the registered modules
  $registrations = media_get_registered_modules();
  // parse the registrations
  foreach ($registrations as $id => $registration) {
    if ($kind) {
      // get the kind that is being looked for
      if ($registration['kind'][$kind]) {
        $kinds[$id] = $registration;
      } 
    }
    else {
       $kinds[$id] = $registration;
    }
  }
  return $kinds;
}


/**
 * Returns a set of formaters which can format the specified 
 * item. If $description is null, all formaters will be returned. If 
 * a set of registered modules can be passed in to narrow the
 * formater options. 
 * @param string $description
 *   file extension to return
 * @param unknown_type $registrations
 * @return array
 */
function media_registration_item_formaters($description = '*', $registrations = null) {
  $formaters = array();
  // get all the registrations if we don't have any
  if (! $registrations) {
    $registrations = media_get_registered_modules();
  }
  // itterate through each of the registered modules and find the formaters
  foreach ($registrations as  $id => $registration) {
    // look for the formater, or just take all
    if ((is_array($registration['kind']['formater']['types']) && in_array($registration['kind']['formater']['types'], $description))
      || $description == '*' 
      || $registration['kind']['formater']['types'] == '*') {
      $formaters[$registration['module']] = $id;
    }
  }
  return $formaters;
}


/**
 * parsing function for the registrations to hand back the kinds 
 * of modules registering
 * @param string $type
 *   only hand back data for the specified type
 * @return array
 */
function media_registration_types($type = null) {
  // get the registered modules
  $registrations = media_get_registered_modules();
  // parse the registrations
  foreach ($registrations as $registration) {
    
  } 
}



/**
 * parsing function for the registrations to hand back the kinds 
 * of modules registering
 * @param string $array
 *   name of the element we want to get data from
 * @return array
 */
function media_registration_data($name) {
  $data = array();
  // get the registered modules
  $registrations = media_get_registered_modules();
  // parse the registrations
  foreach ($registrations as $registration) {
    // get the item that was requested
    $data = array_merge($data, $registration[$name]);
  }
  return $data;
}


/**
 * Build the file browser / uploader 
 */
function media_form () {
  global $user;
  $files = media_get_user_files($user->uid);
  $form['media'] = array(
    '#type' => 'tabset',
    array(
      media_display_user_files_form($files),
      media_display_upload_form(),
    ),    
  );
  return $form;
}

/* *************************************************** */
/* media forms                                         */
/* *************************************************** */

/**
 * Display files in a form element 
 * @param array $files
 *   array of (uri => uri, filename => filename, meta => array(key => value))
 * @param string $title
 *   option title argument
 * @return string
 */
function media_display_user_files_form($files, $title = null) {
  // pase files into options array
  $options = array();
  foreach ($files as $file) {
    $options[$file['uri']] = $file['filename'];
  }
  // parse files into form elemet
  $form['media_files'] = array( 
    '#type' => 'select',
    '#options' => $options,
    '#title' => $title ? $title : '',
    '#size' => 10,
  );
  return $form;
}


/**
 * Display the upload form for the tab 
 * @return string
 */ 
function media_display_upload_form() {
  $form['media_formaters'] = array(
    '#title' => 'formaters placeholder',
    '#value' => '<br />fomaters will be loaded in here via ajax',
  );
  $form['media_upload']['upload'] = array(
    '#type' => 'file',
    '#title' => t('Upload your file'),
    '#size' => 30,
   );
   return $form;
}


/**
 * wrapper to build the media tabs
 * @param array $forms
 * @return array
 */
function media_tabs_form($forms) {
  if (module_exists('tabs')) {
    $form = array();    
    $form['remig'] = array(
      '#type' => 'tabset',
    );
    foreach ($forms as $id => $element) {
      $form['remig']['tab_'. $id] = array(
        '#type' => 'tabpage',
        '#title' => $id,
        'content' => $element,
      );
    }
  }
  else {
    $form = theme('media_no_tab_display', $tabs);
  }
  return $form;
}

/* ***************************************** */
/* media Hook Implementations                */
/* ***************************************** */

/**
 * Implementation of hook_media_user_files_select
 *
 * @param string $node_type
 * @param string $field
 * @param int $uid
 */
function media_media_user_files_select($node_type, $field, $uid) {
  $files = array();
  $results = db_query('SELECT filepath, filename FROM {files} WHERE uid = %d', $uid);
  while ($file = db_fetch_array($results)) {
    $files[] = array(
      'uri' => $file['filepath'],
      'filename' => $file['filename'],
      'meta' => '',
    );
  }
  $return = array( 
    t('My files') => array(
      t('Local') => array( 
        'form' => media_display_user_files_form($files, t('Your files')),
      )
    ),
    t('Add files') => array(
     t('New file') => array(
       'form' => media_display_upload_form(),
     )
    ),    
  );
  return $return;
}
