<?php

function media_gallery_menu() {
  $items = array();

  $items['admin/structure/gallery'] = array(
    'title' => 'Galleries',
    'description' => 'Configure Gallery fields',
    'page callback' => 'media_gallery_blah',
    'access arguments' => array('administer media galleries'),
    'file' => 'media_gallery.admin.inc',
  );

  $items['admin/content/gallery'] = array(
    'title' => 'Galleries',
    'description' => 'Gallery',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('media_gallery_admin_list'),
    'access arguments' => array('administer media galleries'),
    'file' => 'media_gallery.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  
  $items['gallery/add'] = array(
    'title' => 'Create Gallerie',
    'description' => 'Gallery',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('media_gallery_form'),
    'access arguments' => array('create media galleries'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'media_gallery.admin.inc', // Should be pages.inc
  );

  $items['admin/content/gallery/add'] = $items['gallery/add'];

  $items['gallery/%media_gallery/edit'] = array(
    'title' => 'Edit Gallerie',
    'description' => 'Gallery',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('media_gallery_form', 1),
    'access arguments' => array('create media galleries'),
    'file' => 'media_gallery.admin.inc', // Should be pages.inc
  );
  
  $items['admin/content/gallery/%media_gallery/edit'] = $items['gallery/%media_gallery/edit'];
  $items['admin/content/gallery/%media_gallery/edit']['page arguments'] = array('media_gallery_form', 3);

  return $items;
}

function media_gallery_entity_info() {
  $view_modes = array(
    'slideshow' => array('label' => t('Slideshow')),
    'thumbnails' => array('label' => t('Thumbnails')),
  );

  $return = array(
    'gallery' => array(
      'label' => t('Gallery'),
  	  'entity class' => 'Gallery',
      'controller class' => 'EntityAPIController',
      'base table' => 'gallery',
      'fieldable' => TRUE,
      'view modes' => $view_modes,
      'object keys' => array(
        'id' => 'gid',
        //'bundle' => 'type', // @TODO: Why 'type' here...
      ),
      'bundles' => array(
        'gallery' => array(
          'label' => t('Gallery'),
          'admin' => array(
            'path' => 'admin/structure/gallery',
            'access arguments' => array('administer media galleries'),
          ),
        ),
      ),
    ),
  );

  //$media_types = media_type_get_types();

//  foreach ($media_types as $type => $bundle_info) {
//    $return['media']['bundles'][$type] = (array)$bundle_info;
//    $return['media']['bundles'][$type]['admin'] = array(
//      'label' => $bundle_info->label,
//      'path' => 'admin/structure/media/manage/%media_type',
//      'real path' => 'admin/structure/media/manage/' . $type,
//      'bundle argument' => 4,
//      // @TODO: Add an 'administer media types' perm?
//      'access arguments' => array('administer site configuration'),
//    );
//  }

  // @TODO: Do we need to define search-related view modes for attached fields?
  return $return;
}

function media_gallery_field_ui_view_modes_tabs() {
  $view_modes = array(
    'slideshow' => array('label' => t('Slideshow')),
    'thumbnails' => array('label' => t('Thumbnails')),
  );
  $modes = array(
    'basic' => array(
      'view modes' => array_keys($view_modes),
    ),
  );
  return $modes;
}

class Gallery extends EntityDb {
  public function __construct($values = array()) {
    parent::__construct($values, 'gallery');
  }
}

function media_gallery_load($gid) {
  if (!is_numeric($gid)) {
    return;
    //Getting call twice for some reason
  }
  $ids = array($gid);
  $galleries = entity_get_controller('gallery')->load($ids);
  return array_shift($galleries);
}

/**
 * Implement hook_field_widget_info().
 */
function media_gallery_field_widget_info() {
  return array(
    'media_gallery_item' => array(
      'label' => t('Media item for Gallery'),
      'field types' => array('media'),
      'settings' => array(
        'progress_indicator' => 'throbber',
        'allowed_types' => array('image'),
        'allowed_schemes' => array('public', 'private'),
      ),
      'behaviors' => array(
        'multiple values' => FIELD_BEHAVIOR_CUSTOM,
        'default value' => FIELD_BEHAVIOR_NONE,
      ),
    ),
  );
}

/**
 * Implement hook_field_widget_settings_form().
 */
function media_gallery_field_widget_settings_form($field, $instance) {
  return media_field_widget_settings_form($field, $instance);
}


/**
 *  Implement hook_field_widget_form().
 */
function media_gallery_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta = 0) {
  $elements = media_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta = 0);
  foreach (element_children($elements) as $key) {
    $elements[$key]['#process'][] = 'media_gallery_widget_process';
    $elements[$key]['#value_callback'] = 'media_gallery_field_widget_value';
    $elements[$key]['#extended'] = TRUE;
  }
  
  return $elements;
}


/**
 * An element #process callback for the media_managed_file type.
 *
 * Expands the media_managed_file type to include the uri field.
 */
function media_gallery_widget_process($element, &$form_state, $form) {
  $description = NULL;
  $link = NULL;
  $data = !empty($element['#default_value']['data']) ? $element['#default_value']['data'] : NULL;
  if ($data) {
    $description = $data['description'];
    $link = $data['link'];
  }
  
  $element['description'] = array(
    '#type' => 'textfield',
    '#size' => 255,
    '#title' => 'Description',
    '#default_value' => $description,
  );

  $element['link'] = array(
    '#type' => 'textfield',
    '#size' => 100,
    '#title' => 'Link',
    '#default_value' => $link,
  );
  
  return $element;
}

/**
 * The #value_callback for the file_generic field element.
 */
function media_gallery_field_widget_value($element, $input = FALSE, $form_state) {
  $return = array();

  if ($input) {
    $return = $input;
    $return['data'] = array('link' => $input['link'], 'description' => $input['description']);
  }
  
  return media_field_widget_value($element, $return, $form_state);
}



?>
