<?php
//$Id$

/**
 * Implement hook_menu();
 */
function media_gallery_menu() {
  $items = array();

  $items['admin/config/media/gallery'] = array(
    'title' => 'Galleries',
    'description' => 'Configure galleries and slideshows.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('media_gallery_admin_settings'),
    'access arguments' => array('administer media galleries'),
    'file' => 'media_gallery.admin.inc',
  );
  
  $items['admin/content/gallery'] = array(
    'title' => 'Galleries',
    'description' => 'Gallery',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('media_gallery_admin_list'),
    'access arguments' => array('administer media galleries'),
    'file' => 'media_gallery.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  
  $items['gallery/add'] = array(
    'title' => 'Create gallery',
    'description' => 'Gallery',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('media_gallery_form'),
    'access arguments' => array('create media galleries'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'media_gallery.pages.inc', // Should be pages.inc
  );

  $items['admin/content/gallery/add'] = $items['gallery/add'];

  $items['gallery/%media_gallery/edit'] = array(
    'title' => 'Edit gallery',
    'description' => 'Gallery',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('media_gallery_form', 1),
    'access arguments' => array('create media galleries'),
    'file' => 'media_gallery.pages.inc', // Should be pages.inc
    'type' => MENU_LOCAL_TASK,
  );
  
  $items['admin/content/gallery/%media_gallery/edit'] = $items['gallery/%media_gallery/edit'];
  $items['admin/content/gallery/%media_gallery/edit']['type'] = MENU_CALLBACK;
  $items['admin/content/gallery/%media_gallery/edit']['page arguments'] = array('media_gallery_form', 3);

  $items['gallery/%media_gallery/view'] = array(
    'title' => 'View gallery',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10
  );

  $items['gallery/%media_gallery'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'View gallery',
    'description' => 'Gallery',
    'page callback' => 'media_gallery_view',
    'page arguments' => array(1),
    'access arguments' => array('view content'),
    'file' => 'media_gallery.pages.inc',
  );


  return $items;
}

/**
 * Implements hook_block_info
 */
function media_gallery_block_info() {
  $blocks = array();

  $result = db_select('gallery', 'g')
    ->fields('g')
    ->execute()
    ->fetch();



  ///foreach ($ as $hit)
}

/**
 * Implement hook_entity_info();
 */
function media_gallery_entity_info() {
  $view_modes = array(
    'slideshow' => array('label' => t('Slideshow')),
    'thumbnails' => array('label' => t('Thumbnails')),
  );

  $return = array(
    'gallery' => array(
      'label' => t('Gallery'),
  	  'entity class' => 'Gallery',
      'controller class' => 'EntityAPIController',
      'base table' => 'gallery',
      'fieldable' => TRUE,
      'view modes' => $view_modes,
      'entity keys' => array(
        'id' => 'gid',
        //'bundle' => 'type', // @TODO: Why 'type' here...
      ),
      'bundles' => array(
        'gallery' => array(
          'label' => t('Gallery'),
          'admin' => array(
            'path' => 'admin/config/media/gallery',
            'access arguments' => array('administer media galleries'),
          ),
        ),
      ),
    ),
  );
  
  // @TODO: Do we need to define search-related view modes for attached fields?
  return $return;
}


/**
 * Implement hook_field_ui_view_modes_tabs();
 */
function media_gallery_field_ui_view_modes_tabs() {
  $view_modes = array(
    'slideshow' => array('label' => t('Slideshow')),
    'thumbnails' => array('label' => t('Thumbnails')),
  );
  $modes = array(
    'basic' => array(
      'view modes' => array_keys($view_modes),
    ),
  );
  return $modes;
}

/**
 * Menu page argument loader
 */
function media_gallery_load($gid) {
  if (!is_numeric($gid)) {
    return;
    //Getting call twice for some reason
  }
  $ids = array($gid);
  $galleries = entity_get_controller('gallery')->load($ids);
  return array_shift($galleries);
}

/**
 * Implement hook_field_widget_info().
 */
function media_gallery_field_widget_info() {
  return array(
    'media_gallery_item' => array(
      'label' => t('Media item for Gallery'),
      'field types' => array('media'),
      'settings' => array(
        'progress_indicator' => 'throbber',
        'allowed_types' => array('image'),
        'allowed_schemes' => array('public', 'private'),
      ),
      'behaviors' => array(
        'multiple values' => FIELD_BEHAVIOR_DEFAULT,
        'default value' => FIELD_BEHAVIOR_NONE,
      ),
    ),
  );
}

/**
 * Implement hook_field_widget_settings_form().
 */
function media_gallery_field_widget_settings_form($field, $instance) {
  return media_field_widget_settings_form($field, $instance);
}


/**
 *  Implement hook_field_widget_form().
 */
function media_gallery_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $base) {
  $element = media_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $base);
  $element['#process'][] = 'media_gallery_widget_process';
  $element['#value_callback'] = 'media_gallery_field_widget_value';
  $element['#extended'] = TRUE;
  $element['#attached'] = isset($element['#attached']) ? $element['#attached'] : array();
  $element['#attached']['js'] = isset($element['#attached']['js']) ? $element['#attached']['js'] : array();
  $element['#attached']['css'] = isset($element['#attached']['css']) ? $element['#attached']['css'] : array();
  $path = drupal_get_path('module', 'media_gallery');
  $element['#attached']['css'][] = $path . '/media_gallery.css';
  $element['#attached']['js'][] = $path . '/media_gallery.js';
  return $element;
}


/**
 * Build the Gallery object and rebuild the form when receiving an #ajax callback.
 *
 * This is required for the multiple-value fields to work.
 */
function media_gallery_form_submit_build_gallery($form, &$form_state) {
  if ($form_state['values']) {
    $gallery = new Gallery($form_state['values']);
  }
  else {
    $gallery = new Gallery();
  }

  field_attach_submit('gallery', $gallery, $form, $form_state);

  $form_state['gallery'] = $gallery; // uh, wtf is this.
  $form_state['rebuild'] = TRUE;
  return $gallery;
}


/**
 * An element #process callback for media_gallery_item widget
 *
 * Adds description and link fields to the standard media widget.
 */
function media_gallery_widget_process($element, &$form_state, $form) {
  $description = NULL;
  $link = NULL;
  $data = !empty($element['#default_value']['data']) ? $element['#default_value']['data'] : NULL;
  if ($data) {
    $description = $data['description'];
    $link = $data['link'];
  }
  
  $class = empty($element['#default_value']['fid']) ? 'media-widget-open' : 'media-widget-closed' ;
  _form_set_class($element, array($class));

  $element['more_fields'] = array(
    '#type' => 'markup',
    '#markup' => '<a class="edit-description-link" href="#">Edit description and link</a>',
  );

  $element['gallery_field_wrapper'] = array(
    '#type' => 'fieldset',
    '#tree' => FALSE,
    '#prefix' => '<div class="gallery-fields-wrapper">',
    '#suffix' => '</div>',
  );

  // Oh god, there must be a better way to add a wrapper.
  $parents = $element['#parents'];
  array_push($parents, 'description');

  $element['gallery_field_wrapper']['description'] = array(
    '#type' => 'textfield',
    '#size' => 100,
    '#title' => 'Description',
    '#default_value' => $description,
    '#parents' => $parents,
  );

  $parents = $element['#parents'];
  array_push($parents, 'link');
  $element['gallery_field_wrapper']['link'] = array(
    '#type' => 'textfield',
    '#size' => 100,
    '#title' => 'Link',
    '#tree' => TRUE,
    '#default_value' => $link,
    '#parents' => $parents,
  );
  
  return $element;
}

/**
 * The #value_callback for the file_generic field element.
 */
function media_gallery_field_widget_value($element, $input = FALSE, $form_state) {
  $return = array();
  
  if ($input) {
    $return = $input;
    $return['data'] = array('link' => $input['link'], 'description' => $input['description']);
  }
  
  return media_field_widget_value($element, $return, $form_state);
}

/**
 * Implements hook_field_formatter_info();
 */
function media_gallery_field_formatter_info() {
  $info = array();
  $info['media_gallery_slideshow'] = array(
    'label' => t('Slideshow'),
    'field types' => array('media'),
    'behaviors' => array(
      'multiple values' => FIELD_BEHAVIOR_CUSTOM,
    ),
  );
  
  return $info;
}

/**
 * Implements hook_field_formatter_view();
 */
function media_gallery_field_formatter_view($obj_type, $object, $field, $instance, $langcode, $items, $display) {
  $element = array();
  
  if ($display['type'] == 'media_gallery_slideshow') {
    $element = array(
    '#type' => 'container',
    '#attributes' => array('class' => array('jCycle-container')),
    // We need to add settings here somehow... :(
    // Probably from $instance['settings']
    );
    $path = drupal_get_path('module', 'media_gallery');

    $element['#attached'] = array(
      'js' => array(
        $path . 'includes/jquery.cycle.js',
      ),
    );

    foreach ($items as $delta => $item) {
      $element[$delta] = array(
        '#markup' => 'Slide ' . $delta,
        '#prefix' => '<div>',
        '#suffix' => '</div>',
      );
    }
  }

  return $element;
}

//list_field_formatter_view

/**
 * Implement hook_theme
 */
function media_gallery_theme() {
  return array(
    'media_gallery_slideshow' => array(
      'variables' => array('render element' => 'element', 'element' => NULL, 'object' => NULL),
    )
  );
}


function theme_media_gallery_slideshow($variables) {
  $element = $variables['element'];
  
  $presets = styles_presets();
  foreach ($presets as $field_type => $styles) {
    foreach ($styles as $style_name => $style) {

    }
  }
}



/** Classes **/
class Gallery extends EntityDB {
  public function __construct($values = array()) {
    parent::__construct($values, 'gallery');
  }
}